jobs:
- job: Create_Windows_2019_Azure_RDP
  pool:
    vmImage: windows-latest
  steps:
   - checkout: none 
   - script: |
       echo ngrok authtoken "1peMQ7DWRNMlUBubImWmgSruWiV_5hJnoatx1mVyMjzw7R9Vi" > NGROK.bat
       curl -s -O https://raw.githubusercontent.com/huilgetto/Azure_RDP/main/AzureNgrokAutoRegion.bat
       AzureNgrokAutoRegion.bat
     displayName: 'VDS Bağlantı Bilgileri'
